### ISSUE TITLE
Update status blob and add counter data

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-crypto#229]
We discussed a minor improvement required for future development with @hvge and it would help us if we were able to:

- Extend the length of status blob by an additional 32 bytes, so that the result has 64 bytes.
- Return the counter value, as we did for the v2 protocol.

This change will allow us to handle the counter value increments in the future when we implement "partial signature validation"...

**Comment by hvge** [comment]
The status blob in V3 already contains a version signature. Not the activation's version, but the version of status data format. There's "magic" value `0xDECODED1` at the beginning of the structure. Since the V3 SDK, the last byte can contain `0xD2` (or `0xDx` in general), so we can distinguish between the headers.

**Comment by romanstrobl** [comment]
As discussed, we found a way to fit `ctrData` into 32 byte encrypted status blob without completely sacrificing random data. This implementation is prefered because it is compatible with `v2` and hence we can keep one implementation for both versions of activations and minimize changes shortly before release.
